---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: install dep pkgs
  become: yes
  become_user: root
  with_items: '{{virtualbox_dep_pkgs}}'
  package: name={{item}} state=present
    
- name: add pkg mgr config
  include: '{{virtualbox_pkg_mgr}}.yml'
  when: virtualbox_pkg_mgr is defined

- name: install virtualbox
  become: yes
  become_user: root
  package: name={{virtualbox_pkg_name}} state=present

- name: Execute post install tasks
  include: '{{ virtualbox_postinstall_tasks }}'
  when: virtualbox_pkg_mgr is defined
