
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
    update_cache: true

- name: Install kernel-sources
  yum:
    name: 'kernel-devel'
    state: present

- name: Get latest installed kernel version from rpm
  shell: "rpm -q --last kernel | perl -pe 's/^kernel-(\\S+).*/$1/' | head -1"
  register: latest_installed_kernel_stdout

- name: Set fact latest installed kernel
  set_fact:
    latest_installed_kernel: '{{ latest_installed_kernel_stdout.stdout }}'
  when: latest_installed_kernel_stdout.rc == 0
  
- name: debug kernel version
  debug:
    msg: > 
      Current kernel: {{ ansible_kernel }}
      Latest installed Kernel: {{ latest_installed_kernel }}

- name: reboot nodes
  include: reboot.yml
  #  when: ansible_kernel != latest_installed_kernel 

- name: Set kernel directory
  set_fact:
    kernel_directory: "/usr/src/kernels/{{ latest_installed_kernel }}"

- name: "Install VirtualBox driver"
  become: yes
  become_user: root
  shell: /usr/lib/virtualbox/vboxdrv.sh setup
  environment:
    KERN_DIR: "{{ kernel_directory }}"
