
- name: "test if hostname or adress respond to ssh port"
  wait_for:
    timeout: 5
    delay: 1
    host: "{{ item }}"
    port: "{{ ansible_ssh_port }}"
  delegate_to: localhost
  sudo: false
  register: "tested_hosts"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ ansible_ssh_host }}"
    - "{{ ansible_default_ipv4.address }}"
  ignore_errors: true

- name: "find hostname or address from tested hosts for waiting to reboot" 
  set_fact:
    found_hosts: "{{ found_hosts | default([]) + [item.item]}}"
  with_items: "{{ tested_hosts.results }}"
  when: "not item.failed is defined"

- name: "Found hosts for waiting to reboot"
  debug:
    msg: "{{ found_hosts }}"
    
- name: reboot nodes
  shell: 'sleep 2 && shutdown -r +1 "Ansible reboot"'
  async: true
  poll: 0
  ignore_errors: true

- name: wait for server comeback
  wait_for:
    timeout: 400
    delay: 100
    host: "{{ found_hosts[0] }}"
    port: "{{ ansible_ssh_port }}"
  delegate_to: localhost
  sudo: false
  
- name: wait for finalizing startup
  wait_for:
    timeout: 30
  delegate_to: localhost
  sudo: false
