- name: reboot nodes
  shell: 'sleep 2 && shutdown -r +1 "Ansible reboot"'
  async: true
  poll: 0
  ignore_errors: true

- name: wait for server comeback
  wait_for:
    timeout: 400
    delay: 100
    host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    port: "{{ ansible_ssh_port }}"
  delegate_to: localhost
  sudo: false
