---
- name: common | yum-config-manager --add-repo yum_repositories
  yum_repository:
    name: "virtualbox"
    description: "virtualbox"
    baseurl: "{{ virtualbox_rpm_repo_base_url }}"
    gpgkey: "{{ virtualbox_key_url }}"
